const $ = s => document.querySelector(s);
const state = {category:'Tümü', file:null, fileText:'', workflow:[]};
const categories=['Tümü','Veri','Metin','Dosya','Görsel','Developer','Workflow'];
const tools=[
 {id:'csv',title:'CSV Analiz & Temizle',icon:'▦',cat:'Veri',tag:'CSV',desc:'CSV dosyasını profille, duplicate satırları bul ve temizle.'},
 {id:'json',title:'JSON Formatter',icon:'{}',cat:'Veri',tag:'JSON',desc:'JSON doğrula, düzenle veya tek satıra indir.'},
 {id:'text',title:'Metin Temizleyici',icon:'Aa',cat:'Metin',tag:'TEXT',desc:'Satır, boşluk, tekrar ve sıralama işlemlerini tek ekranda yap.'},
 {id:'workflow',title:'Metin Workflow',icon:'⛓',cat:'Workflow',tag:'PIPELINE',desc:'Birden çok metin işlemini sıraya koy ve tek seferde çalıştır.'},
 {id:'hash',title:'SHA-256 Hash',icon:'#',cat:'Dosya',tag:'SECURITY',desc:'Dosyanın SHA-256 parmak izini tarayıcıda hesapla.'},
 {id:'image',title:'Görsel Dönüştürücü',icon:'▧',cat:'Görsel',tag:'IMAGE',desc:'PNG/JPEG/WebP dönüştür, yeniden boyutlandır ve sıkıştır.'},
 {id:'base64',title:'Base64',icon:'64',cat:'Developer',tag:'ENCODE',desc:'Metni Base64 kodla veya çöz.'},
 {id:'url',title:'URL Encode / Decode',icon:'↗',cat:'Developer',tag:'WEB',desc:'URL bileşenlerini güvenli biçimde kodla veya çöz.'},
 {id:'uuid',title:'UUID Generator',icon:'ID',cat:'Developer',tag:'UUID',desc:'Tek seferde çok sayıda UUID v4 üret.'},
 {id:'regex',title:'Regex Tester',icon:'.*',cat:'Developer',tag:'REGEX',desc:'Düzenli ifadeni örnek metin üzerinde test et.'},
 {id:'timestamp',title:'Timestamp Converter',icon:'◷',cat:'Developer',tag:'TIME',desc:'Unix timestamp ile okunabilir tarih arasında dönüşüm yap.'},
 {id:'compare',title:'Metin Karşılaştır',icon:'≠',cat:'Metin',tag:'DIFF',desc:'İki metnin satır bazında farklarını hızlıca gör.'}
];
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),2200)};
const download=(name,data,type='text/plain')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
function renderNav(){ $('#categoryNav').innerHTML=categories.map(c=>`<button class="nav-btn ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join(''); document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderNav();renderTools()}) }
function renderTools(){const q=$('#toolSearch').value.trim().toLowerCase(); const list=tools.filter(t=>(state.category==='Tümü'||t.cat===state.category)&&(!q||`${t.title} ${t.desc} ${t.tag}`.toLowerCase().includes(q))); $('#toolCountText').textContent=`${list.length} araç gösteriliyor`; $('#toolGrid').innerHTML=list.map(t=>`<article class="tool-card" data-tool="${t.id}"><div class="tool-icon">${t.icon}</div><h3>${t.title}</h3><p>${t.desc}</p><span class="tool-tag">${t.tag}</span></article>`).join(''); document.querySelectorAll('.tool-card').forEach(c=>c.onclick=()=>openTool(c.dataset.tool))}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;$('#modalIcon').textContent=t.icon;$('#modalTitle').textContent=t.title;$('#modalDesc').textContent=t.desc;$('#toolBody').innerHTML=toolTemplates[id]();$('#modal').classList.remove('hidden');bindTool(id)}
function closeModal(){ $('#modal').classList.add('hidden'); $('#toolBody').innerHTML='' }
function parseCSV(text){let rows=[],row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(quote&&n==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows}
function csvString(rows){return rows.map(r=>r.map(v=>/[",\n\r]/.test(v)?`"${v.replace(/"/g,'""')}"`:v).join(',')).join('\n')}
function csvStats(rows){if(!rows.length)return null;const headers=rows[0],data=rows.slice(1);const seen=new Set();let dup=0;data.forEach(r=>{const k=JSON.stringify(r);if(seen.has(k))dup++;else seen.add(k)});return {cols:headers.length,rows:data.length,dup,headers,data}}
function uniqueRows(rows){if(rows.length<2)return rows;const out=[rows[0]],seen=new Set();for(const r of rows.slice(1)){const k=JSON.stringify(r);if(!seen.has(k)){seen.add(k);out.push(r)}}return out}
function previewTable(stats){const h=stats.headers;const data=stats.data.slice(0,50);return `<div class="stats-grid"><div class="stat"><b>${stats.rows}</b><span>VERİ SATIRI</span></div><div class="stat"><b>${stats.cols}</b><span>KOLON</span></div><div class="stat"><b>${stats.dup}</b><span>DUPLICATE</span></div><div class="stat"><b>${Math.max(0,stats.rows-stats.dup)}</b><span>BENZERSİZ SATIR</span></div></div><div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${h.map((_,i)=>`<td>${escapeHtml(r[i]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const toolTemplates={
 csv:()=>`<div class="field"><label>CSV içeriği</label><textarea id="csvInput" placeholder="CSV yapıştır veya ana ekrandan dosya bırak…"></textarea></div><div class="action-row"><button class="primary" id="csvAnalyze">Analiz Et</button><button class="secondary" id="csvDedup">Duplicate Temizle</button><button class="secondary" id="csvDownload">CSV İndir</button></div><div id="csvResult"></div>`,
 json:()=>`<div class="tool-layout"><div class="field"><label>JSON</label><textarea id="jsonInput" placeholder='{"name":"Toolbox"}'></textarea><div class="action-row"><button class="primary" id="jsonFormat">Düzenle</button><button class="secondary" id="jsonMin">Minify</button><button class="secondary" id="jsonCopy">Kopyala</button></div></div><div class="field"><label>Sonuç</label><textarea id="jsonOutput" readonly></textarea><div id="jsonStatus" class="result-box">Hazır.</div></div></div>`,
 text:()=>`<div class="tool-layout"><div class="field"><label>Girdi</label><textarea id="textInput"></textarea></div><div class="field"><label>Çıktı</label><textarea id="textOutput" readonly></textarea></div></div><div class="action-row"><button class="secondary tx" data-op="trim">Boşluk Temizle</button><button class="secondary tx" data-op="empty">Boş Satır Sil</button><button class="secondary tx" data-op="unique">Tekrar Sil</button><button class="secondary tx" data-op="sort">A-Z Sırala</button><button class="secondary tx" data-op="upper">BÜYÜK</button><button class="secondary tx" data-op="lower">küçük</button><button class="primary" id="textCopy">Çıktıyı Kopyala</button></div><div id="textStats" class="result-box"></div>`,
 workflow:()=>`<div class="tool-layout"><div><div class="field"><label>Kaynak metin</label><textarea id="wfInput"></textarea></div><div class="action-row"><select id="wfSelect"><option value="trim">Satırları trimle</option><option value="empty">Boş satırları sil</option><option value="unique">Duplicate satırları sil</option><option value="sort">A-Z sırala</option><option value="upper">Büyük harf</option><option value="lower">Küçük harf</option></select><button class="secondary" id="wfAdd">Adım Ekle</button></div><div class="workflow-list" id="wfList"></div></div><div><div class="field"><label>Pipeline çıktısı</label><textarea id="wfOutput" readonly></textarea></div><div class="action-row"><button class="primary" id="wfRun">Workflow'u Çalıştır</button><button class="danger" id="wfClear">Temizle</button></div></div></div>`,
 hash:()=>`<div class="field"><label>Dosya seç</label><input class="text-input" id="hashFile" type="file"></div><div class="action-row"><button class="primary" id="hashRun">SHA-256 Hesapla</button></div><div id="hashResult" class="result-box">Dosya bekleniyor.</div>`,
 image:()=>`<div class="tool-layout"><div><div class="field"><label>Görsel</label><input class="text-input" id="imgFile" type="file" accept="image/*"></div><div class="stats-grid"><div class="field"><label>Genişlik</label><input class="text-input" id="imgW" type="number" min="1"></div><div class="field"><label>Yükseklik</label><input class="text-input" id="imgH" type="number" min="1"></div><div class="field"><label>Format</label><select id="imgFormat"><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></div><div class="field"><label>Kalite</label><input class="text-input" id="imgQ" type="number" min="10" max="100" value="85"></div></div><button class="primary" id="imgRun">Dönüştür & İndir</button></div><div id="imgPreview" class="result-box">Önizleme burada görünecek.</div></div>`,
 base64:()=>`<div class="tool-layout"><div class="field"><label>Girdi</label><textarea id="b64Input"></textarea></div><div class="field"><label>Çıktı</label><textarea id="b64Output" readonly></textarea></div></div><div class="action-row"><button class="primary" id="b64Enc">Encode</button><button class="secondary" id="b64Dec">Decode</button></div>`,
 url:()=>`<div class="tool-layout"><div class="field"><label>Girdi</label><textarea id="urlInput"></textarea></div><div class="field"><label>Çıktı</label><textarea id="urlOutput" readonly></textarea></div></div><div class="action-row"><button class="primary" id="urlEnc">Encode</button><button class="secondary" id="urlDec">Decode</button></div>`,
 uuid:()=>`<div class="field"><label>Adet</label><input id="uuidCount" class="text-input" type="number" min="1" max="1000" value="10"></div><div class="action-row"><button class="primary" id="uuidRun">Üret</button><button class="secondary" id="uuidCopy">Kopyala</button></div><textarea id="uuidOut" readonly></textarea>`,
 regex:()=>`<div class="field"><label>Regex</label><input id="regexPattern" class="text-input" placeholder="\\b\\w{5,}\\b"></div><div class="field"><label>Flag</label><input id="regexFlags" class="text-input" value="gi"></div><div class="field"><label>Test metni</label><textarea id="regexText"></textarea></div><div class="action-row"><button class="primary" id="regexRun">Test Et</button></div><div id="regexResult" class="result-box"></div>`,
 timestamp:()=>`<div class="field"><label>Unix timestamp (saniye veya milisaniye)</label><input id="tsInput" class="text-input" placeholder="1700000000"></div><div class="action-row"><button class="primary" id="tsRun">Tarihe Çevir</button><button class="secondary" id="tsNow">Şimdi</button></div><div id="tsResult" class="result-box"></div>`,
 compare:()=>`<div class="tool-layout"><div class="field"><label>Metin A</label><textarea id="cmpA"></textarea></div><div class="field"><label>Metin B</label><textarea id="cmpB"></textarea></div></div><div class="action-row"><button class="primary" id="cmpRun">Karşılaştır</button></div><div id="cmpResult" class="result-box"></div>`
};
function transformText(s,op){let lines=s.split(/\r?\n/);if(op==='trim')return lines.map(x=>x.trim()).join('\n').trim();if(op==='empty')return lines.filter(x=>x.trim()).join('\n');if(op==='unique')return [...new Set(lines)].join('\n');if(op==='sort')return lines.sort((a,b)=>a.localeCompare(b,'tr')).join('\n');if(op==='upper')return s.toLocaleUpperCase('tr-TR');if(op==='lower')return s.toLocaleLowerCase('tr-TR');return s}
function bindTool(id){
 if(id==='csv'){const inp=$('#csvInput');if(state.fileText&&state.file?.name.toLowerCase().endsWith('.csv'))inp.value=state.fileText;let current=null;const analyze=()=>{const rows=parseCSV(inp.value);current=rows;const st=csvStats(rows);$('#csvResult').innerHTML=st?previewTable(st):'<div class="result-box">CSV verisi bulunamadı.</div>'};$('#csvAnalyze').onclick=analyze;$('#csvDedup').onclick=()=>{const rows=parseCSV(inp.value);const clean=uniqueRows(rows);inp.value=csvString(clean);current=clean;analyze();toast('Duplicate satırlar temizlendi')};$('#csvDownload').onclick=()=>download('cleaned.csv',csvString(current||parseCSV(inp.value)),'text/csv;charset=utf-8');if(inp.value)analyze()}
 if(id==='json'){if(state.fileText&&state.file?.name.toLowerCase().endsWith('.json'))$('#jsonInput').value=state.fileText;const run=min=>{try{const o=JSON.parse($('#jsonInput').value);$('#jsonOutput').value=JSON.stringify(o,null,min?0:2);$('#jsonStatus').textContent='✓ Geçerli JSON';}catch(e){$('#jsonStatus').textContent='✕ '+e.message}};$('#jsonFormat').onclick=()=>run(false);$('#jsonMin').onclick=()=>run(true);$('#jsonCopy').onclick=()=>navigator.clipboard.writeText($('#jsonOutput').value).then(()=>toast('Kopyalandı'));}
 if(id==='text'){const input=$('#textInput');input.value=state.fileText||'';const apply=op=>{const out=transformText(input.value,op);$('#textOutput').value=out;const w=(out.match(/\S+/g)||[]).length,l=out?out.split(/\r?\n/).length:0;$('#textStats').textContent=`${out.length} karakter • ${w} kelime • ${l} satır`};document.querySelectorAll('.tx').forEach(b=>b.onclick=()=>apply(b.dataset.op));$('#textCopy').onclick=()=>navigator.clipboard.writeText($('#textOutput').value).then(()=>toast('Kopyalandı'));apply('trim')}
 if(id==='workflow'){state.workflow=[];const labels={trim:'Satırları trimle',empty:'Boş satırları sil',unique:'Duplicate satırları sil',sort:'A-Z sırala',upper:'Büyük harf',lower:'Küçük harf'};const render=()=>$('#wfList').innerHTML=state.workflow.map((x,i)=>`<div class="workflow-step"><span>${i+1}. ${labels[x]}</span><button class="icon-btn" data-i="${i}">✕</button></div>`).join('')||'<div class="result-box">Henüz adım eklenmedi.</div>';$('#wfInput').value=state.fileText||'';$('#wfAdd').onclick=()=>{state.workflow.push($('#wfSelect').value);render();document.querySelectorAll('#wfList button[data-i]').forEach(b=>b.onclick=()=>{state.workflow.splice(+b.dataset.i,1);render()})};$('#wfRun').onclick=()=>{$('#wfOutput').value=state.workflow.reduce((s,op)=>transformText(s,op),$('#wfInput').value);toast(`${state.workflow.length} adım çalıştı`)};$('#wfClear').onclick=()=>{state.workflow=[];render()};render()}
 if(id==='hash'){$('#hashRun').onclick=async()=>{const f=$('#hashFile').files[0];if(!f)return toast('Önce dosya seç');const h=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());$('#hashResult').textContent=[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}}
 if(id==='image'){let image=null,name='image';$('#imgFile').onchange=e=>{const f=e.target.files[0];if(!f)return;name=f.name.replace(/\.[^.]+$/,'');const url=URL.createObjectURL(f);image=new Image();image.onload=()=>{$('#imgW').value=image.naturalWidth;$('#imgH').value=image.naturalHeight;$('#imgPreview').innerHTML=`<img src="${url}" style="max-width:100%;max-height:320px;border-radius:9px">`};image.src=url};$('#imgRun').onclick=()=>{if(!image)return toast('Önce görsel seç');const c=document.createElement('canvas');c.width=+$('#imgW').value||image.naturalWidth;c.height=+$('#imgH').value||image.naturalHeight;c.getContext('2d').drawImage(image,0,0,c.width,c.height);const type=$('#imgFormat').value,q=(+$('#imgQ').value||85)/100;c.toBlob(blob=>{const ext=type.split('/')[1].replace('jpeg','jpg');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${name}.${ext}`;a.click()},type,q)}}
 if(id==='base64'){$('#b64Enc').onclick=()=>{$('#b64Output').value=btoa(unescape(encodeURIComponent($('#b64Input').value)))};$('#b64Dec').onclick=()=>{try{$('#b64Output').value=decodeURIComponent(escape(atob($('#b64Input').value)))}catch(e){toast('Geçersiz Base64')}}}
 if(id==='url'){$('#urlEnc').onclick=()=>$('#urlOutput').value=encodeURIComponent($('#urlInput').value);$('#urlDec').onclick=()=>{try{$('#urlOutput').value=decodeURIComponent($('#urlInput').value)}catch(e){toast('Geçersiz URL encoding')}}}
 if(id==='uuid'){$('#uuidRun').onclick=()=>{$('#uuidOut').value=Array.from({length:Math.min(1000,Math.max(1,+$('#uuidCount').value||1))},()=>crypto.randomUUID()).join('\n')};$('#uuidCopy').onclick=()=>navigator.clipboard.writeText($('#uuidOut').value).then(()=>toast('Kopyalandı'));$('#uuidRun').click()}
 if(id==='regex'){$('#regexRun').onclick=()=>{try{const r=new RegExp($('#regexPattern').value,$('#regexFlags').value),m=[...$('#regexText').value.matchAll(r)];$('#regexResult').textContent=m.length?`${m.length} eşleşme:\n\n`+m.map((x,i)=>`${i+1}. ${x[0]} @ ${x.index}`).join('\n'):'Eşleşme yok.'}catch(e){$('#regexResult').textContent='Regex hatası: '+e.message}}}
 if(id==='timestamp'){$('#tsRun').onclick=()=>{let n=Number($('#tsInput').value);if(!Number.isFinite(n))return toast('Geçerli sayı gir');if(n<1e12)n*=1000;const d=new Date(n);$('#tsResult').textContent=`Yerel: ${d.toLocaleString('tr-TR')}\nISO: ${d.toISOString()}\nUnix sn: ${Math.floor(n/1000)}\nUnix ms: ${n}`};$('#tsNow').onclick=()=>{$('#tsInput').value=Date.now();$('#tsRun').click()}}
 if(id==='compare'){$('#cmpRun').onclick=()=>{const a=$('#cmpA').value.split(/\r?\n/),b=$('#cmpB').value.split(/\r?\n/),max=Math.max(a.length,b.length),out=[];for(let i=0;i<max;i++){if(a[i]!==b[i])out.push(`Satır ${i+1}:\n- ${a[i]??''}\n+ ${b[i]??''}`)}$('#cmpResult').textContent=out.length?`${out.length} farklı satır\n\n${out.join('\n\n')}`:'Metinler aynı.'}}
}
async function handleFile(f){state.file=f;state.fileText='';$('#fileInfo').textContent=`${f.name} • ${(f.size/1024).toFixed(1)} KB`;const ext=f.name.split('.').pop().toLowerCase();if(['csv','json','txt','md','log'].includes(ext)){state.fileText=await f.text(); if(ext==='csv')openTool('csv');else if(ext==='json')openTool('json');else openTool('text')}else if(['png','jpg','jpeg','webp'].includes(ext)){openTool('image');toast('Görsel dönüştürücüyü açtım; dosyayı alana seçebilirsin.')}else toast('Dosya alındı; uygun aracı seçebilirsin.')}
function smartSearch(q){q=q.trim().toLowerCase();if(!q)return;const map=[['json','json'],['csv','csv'],['duplicate','csv'],['tekrar','csv'],['metin','text'],['temiz','text'],['base64','base64'],['regex','regex'],['uuid','uuid'],['hash','hash'],['sha','hash'],['görsel','image'],['resim','image'],['workflow','workflow'],['pipeline','workflow'],['timestamp','timestamp'],['url','url']];const hit=map.find(([k])=>q.includes(k));if(hit)openTool(hit[1]);else{const t=tools.find(t=>`${t.title} ${t.desc}`.toLowerCase().includes(q));if(t)openTool(t.id);else toast('Bu komut için hazır araç bulamadım.') }}
$('#toolSearch').oninput=renderTools;$('#pickFileBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>e.target.files[0]&&handleFile(e.target.files[0]);['dragenter','dragover'].forEach(ev=>$('#dropZone').addEventListener(ev,e=>{e.preventDefault();$('#dropZone').classList.add('drag')}));['dragleave','drop'].forEach(ev=>$('#dropZone').addEventListener(ev,e=>{e.preventDefault();$('#dropZone').classList.remove('drag')}));$('#dropZone').addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandInput').focus()}if(e.key==='Escape')closeModal()});$('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter')smartSearch(e.target.value)});$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('tb-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('tb-theme')==='light')document.body.classList.add('light');
renderNav();renderTools();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
(async()=>{if(location.protocol==='file:')return;try{const wasm=await import('./wasm-pkg/toolbox_core.js');await wasm.default();window.ToolboxWasm=wasm;$('#engineBadge').textContent='Rust/WASM Engine';$('#engineBadge').classList.add('wasm')}catch{}})();
